config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :things do
    resources :bookings, only: [:new, :create]
  end
  get 'dashboard', to: 'pages#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :thing
  belongs_to :user
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
end

app/models/thing.rb
class Thing < ApplicationRecord
  CATEGORY_LIST = ['Outillage & Travaux', 'Matériel de jardin', 'Electroménager', 'Maison & Déco', 'Evénement', 'High Tech', 'Loisirs']
  include PgSearch

  belongs_to :owner, class_name: "User", foreign_key: :user_id
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  has_many :users, through: :bookings
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  mount_uploader :photo, PhotoUploader

  validates :title, presence: true
  validates :category, presence: true, inclusion: { in: Thing::CATEGORY_LIST }
  validates :address, presence: true

  pg_search_scope :search_by_title,
    against: [ :title],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :things, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :things, through: :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone])

    # # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  # Pundit: white-list approach.
  after_action :verify_authorized, except: [:index], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @thing = Thing.find(params[:thing_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.thing = Thing.find(params[:thing_id])
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:arrival_date, :departure_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
    @bookings = current_user.bookings
    @things = Thing.where(owner: current_user)
  end

end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @things = policy_scope(Thing)
      .where.not(latitude: nil, longitude: nil)
      .order(created_at: :desc)
    if params[:query].present?
      @things = @things.search_by_title(params[:query])
    else
      @things
    end
    @markers = @things.map do |thing|
      {
        lng: thing.longitude,
        lat: thing.latitude,
        infoWindow: { content: render_to_string(partial: "/things/map_window", locals: { thing: thing }) }
      }
    end
  end

  def show
  end

  def new
    @thing = Thing.new
    authorize @thing
  end

  def create
    @thing = Thing.new(thing_params)
    @thing.owner = current_user
    authorize @thing
    if @thing.save
      redirect_to thing_path(@thing)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @thing.update(thing_params)
      redirect_to thing_path(@thing)
    else
      render :edit
    end
  end

  def destroy
    @thing.destroy
    redirect_to things_path
  end

  private

  def thing_params
    params.require(:thing).permit(:title, :description, :photo, :price, :address, :category, :days_nb_min, :days_nb_max, :starting_available_date, :ending_available_date)
  end

  def set_thing
    @thing = Thing.find(params[:id])
    authorize @thing
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_booking_form.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= simple_form_for [thing, booking] do |f| %>
      <%= f.input :arrival_date, as: :date, html5: true, label: "Début de la location" %>
      <%= f.input :departure_date, as: :date, html5: true, label: "Fin de la location" %>
      <%= f.button :submit, "Réserver", class: 'btn btn-primary'%>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Réserver : <%= @thing.title %></h1>
    </div>
  </div>

  <%= render 'booking_form', thing: @thing, booking: @booking %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_pack_tag "map" %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'components/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <h1>Mon dashboard</h1>

      <h2 class="dashboard-title">Liste de mes réservations :</h2>
      <ul class="dashboard-list">
        <% @bookings.each do |booking| %>
          <li><%= link_to booking.thing.title, thing_path(booking.thing) %> du <%= booking.arrival_date %> au <%= booking.departure_date %></li>
        <% end %>
      </ul>
      <h2 class="dashboard-title">Liste de mes objets :</h2>
      <ul class="dashboard-list">
        <% @things.each do |thing| %>
          <li><%= link_to thing.title, thing_path(thing) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<%= render 'components/banner' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <%= link_to "Voir tous les objets", things_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Mon tableau de bord", dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "stallone.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profil") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Réglages") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Se déconnecter") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Se connecter"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <%= link_to "Mon tableau de bord", dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %>
      </ul>
    </div>
  </div>
</div>

app/views/things/_form.html.erb
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <%= simple_form_for thing do |f| %>
        <%= f.input :title,label: "Nom de l'objet"  %>
        <%= f.input :description %>
        <%= f.input :price,label: "Prix"  %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.input :address,label: "Adresse"  %>
        <%= f.input :category, collection: Thing::CATEGORY_LIST, label: "Catégorie"  %>
        <%= f.input :days_nb_min, label: "Jour minimum de location"  %>
        <%= f.input :days_nb_max, label: "Jour maximum de location"  %>
        <%= f.input :starting_available_date, as: :date, html5: true, label: "Début de disponibilité"  %>
        <%= f.input :ending_available_date, as: :date, html5: true, label: "Fin de disponibilité"  %>
        <%= f.button :submit, "Enregistrer mon objet", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

app/views/things/_map_window.html.erb
<h6><strong><%= link_to thing.title, thing_path(thing)%></strong></h6>
<p><%= thing.category %>
<br><%= thing.price%>€</p>

app/views/things/edit.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Modifier mon objet</h1>
    </div>
  </div>

  <%= render 'form', thing: @thing %>

</div>

app/views/things/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-sm-7">
      <% @things.each do |thing| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="card"
    style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
           url('<%= thing.photo %>')">
            <div class="card-category"><%= thing.category %></div>
            <div class="card-description">
              <h2><%= thing.title %> | <%= thing.price %>€</h2>
            </div>

            <%= link_to "", thing_path(thing), class: "card-link" %>
          </div>
        </div>
      <% end %>
      <% if policy(Thing).create? %>
        <%= link_to "Ajouter un objet", new_thing_path %>
      <% end %>
    </div>
    <div class="col-xs-12 col-sm-5">
      <div id="map" style="width: 100%; height: 600px;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>" >
      </div>
    </div>
  </div>

</div>

app/views/things/new.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Ajouter mon objet</h1>
    </div>
  </div>

  <%= render 'form', thing: @thing %>

</div>

app/views/things/show.html.erb
<div class="container">

  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <div class="thumbnail" id="thing-card">
        <div class="caption">
          <h3><%= @thing.title %> <em><%= @thing.price %>€</em></h3>
          <p><strong>Catégorie : </strong><%= @thing.category %></p>
          <p><strong>Disponibilités : </strong><%= @thing.starting_available_date %> - <%= @thing.ending_available_date %></p>
          <p><%= @thing.description %></p>
          <p>
            <% if policy(@thing).edit? %>
              <%= link_to "Mettre à jour", edit_thing_path(@thing), class: "btn btn-info" %>
            <% end %>
            <% if policy(@thing).destroy? %>
              <%= link_to "Supprimer", thing_path(@thing), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-info"%>
            <% else %>
              <%= link_to "Réserver cet objet", new_thing_booking_path(@thing), class: "btn btn-info"%>
            <% end %>
          </p>
        </div>
        <%= cl_image_tag @thing.photo.url(:thumnail) %>
      </div>
      <p><%= link_to "<< Retour à la liste de tous les objets", things_path %></p>
    </div>
  </div>



</div>